---
- name: Install required packages for Caddy repository
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
    update_cache: true

- name: Add Caddy repository key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /usr/share/keyrings/caddy-stable-archive-keyring.asc
    mode: '0644'

- name: Add Caddy repository
  ansible.builtin.deb822_repository:
    name: caddy-stable
    types: deb
    uris: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
    suites: any-version
    components:
      - main
    signed_by: /usr/share/keyrings/caddy-stable-archive-keyring.asc
    state: present

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true

- name: Install Caddy configuration
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: caddy
    mode: '0644'
    validate: 'caddy validate --config %s --adapter caddyfile'
  notify: Restart Caddy

- name: Enable and start Caddy
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started
