---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: safe

- name: Install base packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - git
      - vim
      - sudo
      - uidmap
      - dbus-user-session
      - fuse-overlayfs
      - passt
    state: present

